version: '3.1'
services:
  https-portal:
    image: steveltn/https-portal:1.3.0
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - trans
    restart: always
    environment:
      DOMAINS: 'trans-akka.ml -> http://trans'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

      # Disable checking request body size
      # (from: https://github.com/SteveLTN/https-portal/tree/273ed46185e4acfa6beb21719b284752aaa22cb3#configure-nginx-through-environment-variables)
      CLIENT_MAX_BODY_SIZE: 0
    volumes:
      - ./docker_volumes/ssl_certs:/var/lib/https-portal

  trans:
    image: nwtgck/trans-server-akka:v1.17.0
    restart: always
    expose:
      - "80"
    volumes:
      - ./docker_volumes/trans-db:/trans/db
