
version: '3.1'
services:
  https-portal:
    image: steveltn/https-portal:1.3.0
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - trans
    restart: always
    environment:
      DOMAINS: 'trans-akka.ml -> http://trans'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  trans:
    image: nwtgck/trans-server-akka:v1.17.0
    expose:
      - "80"
